version: "3"

services:
  app:
    container_name: app
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - SESSION_NAME=task_helper_session
      - SECRET_SESSION=fjkweivknal
      - PORT=3000
      - SECRET_TOKEN=fgglkjsg34tklfd
      - DB_URL=mongodb://mongo:mongo@mongo:27017/?authSource=admin

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=mongo